spring.application.name=allocore
spring.datasource.url=jdbc:postgresql://localhost:5432/allocore
spring.datasource.username=postgres
spring.datasource.password=2806

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect